steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install packages.
- name: 'node:10'
  dir: 'tfjs-backend-webgl'
  id: 'yarn'
  entrypoint: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build deps.
- name: 'node:10'
  dir: 'tfjs-backend-webgl'
  id: 'build-deps'
  entrypoint: 'yarn'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Build.
- name: 'node:10'
  dir: 'tfjs-backend-webgl'
  id: 'build'
  entrypoint: 'yarn'
  args: ['build-ci']
  waitFor: ['yarn', build-deps]

# Lint.
- name: 'node:10'
  dir: 'tfjs-backend-webgl'
  id: 'lint'
  entrypoint: 'yarn'
  args: ['lint']
  waitFor: ['yarn', 'build-deps']

# Run tests.
- name: 'node:10'
  dir: 'tfjs-backend-webgl'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps', 'lint']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1', 'NIGHTLY=$_NIGHTLY']
  secretEnv: ['BROWSERSTACK_KEY']

# General configuration
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 3600s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
