steps:
# Install top-level deps.
- name: 'gcr.io/learnjs-174218/release'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

- name: 'gcr.io/learnjs-174218/release'
  id: 'bazel-tests'
  entrypoint: 'yarn'
  args: ['run', 'bazelisk', 'test', '//tfjs-backend-webgl:browserstack_bs_ios_11_tfjs-backend-webgl1_test', '--test_output=all', '--//:grep="Parallel compilation"']
  env:
    - 'BROWSERSTACK_USERNAME=deeplearnjs1'
    - 'NIGHTLY=$_NIGHTLY'
  waitFor: ['yarn-common']
  secretEnv: ['BROWSERSTACK_KEY']

secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 3600s
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  machineType: 'N1_HIGHCPU_32'
  substitution_option: 'ALLOW_LOOSE'
