steps:
# Install common dependencies.
- name: 'node:12'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Run tests in browser.
- name: 'node:12'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'test-wasm'
  args: ['test-ci']
  waitFor: ['yarn-common']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1']
  secretEnv: ['BROWSERSTACK_KEY']

# Run C++ tests.
- name: 'node:12'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'test-cc'
  args: ['test-cc']
  waitFor: ['test-wasm']

# Check bundle size.
- name: 'node:12'
  dir: 'tfjs-backend-wasm'
  id: 'test-bundle-size'
  entrypoint: 'yarn'
  args: ['test-bundle-size']
  waitFor: ['test-wasm']

# Lint bazel files.
- name: 'node:12'
  dir: 'tfjs-backend-wasm'
  id: 'buildifier'
  entrypoint: 'yarn'
  args: ['buildifier-ci']
  waitFor: ['test-wasm']

# General configuration
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
