steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install packages.
- name: 'node:10'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Install build-deps.
- name: 'node:10'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'build-deps'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Build.
- name: 'gcr.io/learnjs-174218/wasm'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'bash'
  id: 'build'
  args: ['./scripts/build-ci.sh']
  waitFor: ['yarn', 'build-deps']

# Lint.
- name: 'node:10'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn', 'build-deps']

# Run JS tests.
- name: 'node:10'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'test-wasm'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps', 'build', 'lint']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1', 'NIGHTLY=$_NIGHTLY']
  secretEnv: ['BROWSERSTACK_KEY']

# Run C++ tests.
- name: 'gcr.io/learnjs-174218/wasm'
  dir: 'tfjs-backend-wasm'
  entrypoint: 'yarn'
  id: 'test-cc'
  args: ['test-cc']
  waitFor: ['build']

# Check bundle size.
- name: 'gcr.io/learnjs-174218/wasm'
  dir: 'tfjs-backend-wasm'
  id: 'test-bundle-size'
  entrypoint: 'yarn'
  args: ['test-bundle-size']
  waitFor: ['yarn', 'build-deps', 'build']

# Lint bazel files.
- name: 'node:10'
  dir: 'tfjs-backend-wasm'
  id: 'buildifier'
  entrypoint: 'yarn'
  args: ['buildifier-ci']
  waitFor: ['yarn']

# General configuration
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 3600s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
