steps:
# Install top-level deps.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']

# Run test_affected_packages to test packages affected by the change.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'test-packages'
  args: ['test-packages']
  waitFor: ['yarn']
  env:
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BRANCH_NAME=$BRANCH_NAME'
  - 'BASE_BRANCH=$_BASE_BRANCH'

# General settings.
timeout: 3600s
logsBucket: 'gs://tfjs-build-logs'
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
