os:
  - osx
  - windows
language: node_js
node_js:
  - "10"
script:
  - ./scripts/test-ci.sh
  - ./scripts/test-ts-integration.sh
cache: yarn
git:
  depth: 5
notifications:
  email:
    recipients:
      - tensorflowjs-build@google.com
    on_success: never
    on_failure: always
    on_pull_requests: false
env:
  - YARN_GPG=no
