steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install tfjs-node dependencies.
- name: 'node:10'
  dir: 'tfjs-node'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['build-union']

# Unit tests.
- name: 'node:10'
  dir: 'tfjs-node'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test-ci']
  waitFor: ['yarn']

# Integration test.
- name: 'node:10'
  dir: 'tfjs-node'
  entrypoint: 'yarn'
  id: 'test-ts-integration'
  args: ['test-ts-integration']
  waitFor: ['yarn', 'test']

# CPU / GPU package alignment.
- name: 'node:10'
  dir: 'tfjs-node'
  entrypoint: 'yarn'
  id: 'ensure-cpu-gpu-packages-align'
  args: ['ensure-cpu-gpu-packages-align']
  waitFor: ['yarn']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
