
steps:

# Install common dependencies.
- name: 'node:16'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Install tfjs-converter dependencies.
- name: 'node:16'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Lint.
- name: 'node:16'
  dir: 'tfjs-converter'
  id: 'lint'
  entrypoint: 'yarn'
  args: ['lint']
  waitFor: ['yarn']

- name: 'node:16'
  id: 'create-pips'
  entrypoint: 'bash'
  args:
    - './tfjs-converter/scripts/create_python_pips.sh'
  waitFor: ['yarn-common']

# Run python tests.
- name: 'gcr.io/google-appengine/python'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  id: 'test-python-pip'
  args: ['./build-pip-package.sh', '--test', '/tmp/tfjs-pips']
  waitFor: ['create-pips']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'N1_HIGHCPU_8'
