steps:

# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Install converter dependencies.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Run lint.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn']

# Generate json file.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'gen-json'
  args: ['gen-json', '--test']
  waitFor: ['yarn']

# Build the project.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build']
  waitFor: ['gen-json']

# Run javascript tests.
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'test-js'
  args: ['test-ci']
  waitFor: ['build']
  env: ['NIGHTLY=$_NIGHTLY']

# Run python tests.
- name: 'gcr.io/google-appengine/python'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  id: 'python-build'
  args: ['./build-pip-package.sh', '--test', '/tmp/tfjs-pips']
  waitFor: ['gen-json']

- name: 'python:2'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  args: ['./run-python-tests.sh']
  waitFor: ['python-build']

- name: 'python:3.6'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  args: ['./run-python-tests.sh']
  waitFor: ['python-build']

- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'test-snippets'
  args: ['test-snippets']
  waitFor: ['yarn']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'N1_HIGHCPU_8'
