steps:

# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Install converter dependencies
- name: 'node:10'
  dir: 'tfjs-converter'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Bazel tests
# These use a remote cache and only re-run if changes occurred, so we run them
# in every build.
- name: 'node:10'
  id: 'create-pips'
  entrypoint: 'bash'
  args:
    - './tfjs-converter/scripts/create_python_pips.sh'
  waitFor: ['yarn-common']

# Run python tests.
- name: 'gcr.io/google-appengine/python'
  dir: 'tfjs-converter/python'
  entrypoint: 'bash'
  args: ['./build-pip-package.sh', '--test-nightly', '/tmp/tfjs-pips']
  waitFor: ['create-pips']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
