steps:

# Install packages.
- name: 'node:10'
  dir: 'tfjs-inference'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']

# JS Test.
- name: 'node:10'
  dir: 'tfjs-inference'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test-ci']
  waitFor: ['yarn']

# Build binaries.
- name: 'node:10'
  dir: 'tfjs-inference'
  entrypoint: 'yarn'
  id: 'build-binary'
  args: ['build-binary']
  waitFor: ['test']

# Python Test.
- name: 'node:10'
  dir: 'tfjs-inference'
  entrypoint: 'yarn'
  id: 'test-python'
  args: ['test-python']
  waitFor: ['build-binary']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
