steps:
# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Install packages.
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build deps.
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'build-deps'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Build.
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build-ci']
  waitFor: ['yarn', 'build-deps']

# Lint.
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn', 'build-deps']

# Run javascript tests
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'test-browser'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps', 'lint']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1', 'NIGHTLY=$_NIGHTLY']
  secretEnv: ['BROWSERSTACK_KEY']

# Run python tests
- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'tfjs2keras-js'
  args: ['tfjs2keras-js']
  waitFor: ['test-browser']

- name: 'python:2'
  dir: 'tfjs-layers'
  entrypoint: 'bash'
  id: 'tfjs2keras-py'
  args: ['-c', './scripts/tfjs2keras-py.sh --stable && ./scripts/tfjs2keras-py.sh --stable --tfkeras']
  waitFor: ['tfjs2keras-js']

- name: 'node:10'
  dir: 'tfjs-layers'
  entrypoint: 'yarn'
  id: 'test-snippets'
  args: ['test-snippets']
  waitFor: ['build']
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
