steps:

# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Run tests in node.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test-ci']
  waitFor: ['yarn-common']

# Run data snippets tests.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'test-snippets'
  args: ['test-snippets']
  waitFor: ['test']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
