steps:

# Install common dependencies.
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn-common'
  args: ['install']

# Build core from master.
- name: 'node:10'
  dir: 'tfjs-data'
  id: 'build-core'
  entrypoint: 'yarn'
  args: ['build-core-ci']
  waitFor: ['yarn-common']

# Build layers from master.
- name: 'node:10'
  dir: 'tfjs-data'
  id: 'build-layers'
  entrypoint: 'yarn'
  args: ['build-layers-ci']
  waitFor: ['build-core']

# Install data dependencies.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['build-layers']

# Run lint.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn']

# Build the project.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build-ci']
  waitFor: ['yarn']

# Run tests in node.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test']
  waitFor: ['build']

# Run data snippets tests.
- name: 'node:10'
  dir: 'tfjs-data'
  entrypoint: 'yarn'
  id: 'test-snippets'
  args: ['test-snippets']
  waitFor: ['build']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
