steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install webgpu dependencies.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  id: 'yarn'
  entrypoint: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build deps.
# TODO(Yunfei): Change id to 'build-deps' after webgpu dependencies write into
# packange_dependencies.json
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  id: 'build-deps-for-webgpu'
  entrypoint: 'yarn'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Lint.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  id: 'lint'
  entrypoint: 'yarn'
  args: ['lint']
  waitFor: ['yarn', 'build-deps-for-webgpu']

# Run tests.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  entrypoint: 'yarn'
  id: 'test-webgpu'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps-for-webgpu', 'lint']

# General configuration
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
