steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install webgpu dependencies.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  id: 'yarn'
  entrypoint: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build core from master.
# Named 'build-deps' to prevent
# it from being run in CI.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  id: 'build-deps'
  entrypoint: 'yarn'
  args: ['build-core']
  waitFor: ['yarn-common']

# Run tests.
- name: 'node:10'
  dir: 'tfjs-backend-webgpu'
  entrypoint: 'yarn'
  id: 'test-webgpu'
  args: ['test-ci']
  waitFor: ['build-deps', 'yarn']

# General configuration
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
