steps:
# Prepare tfjs-node-gpu folder, copy files from tfjs-node.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  id: 'prep-gpu'
  entrypoint: 'yarn'
  args: ['prep-gpu']

# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']
  waitFor: ['prep-gpu']

# Install packages.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Build add-on.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'build-addon'
  args: ['build-addon-from-source']
  waitFor: ['yarn']

# Build deps.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'build-deps'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Build.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build-ci']
  waitFor: ['yarn', 'build-deps']

# Lint.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn', 'build-deps']

# Unit tests.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'test'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps', 'lint']

# Integration test.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'test-ts-integration'
  args: ['test-ts-integration']
  waitFor: ['test']

# CPU / GPU package alignment.
- name: 'node:10'
  dir: 'tfjs-node-gpu'
  entrypoint: 'yarn'
  id: 'ensure-cpu-gpu-packages-align'
  args: ['ensure-cpu-gpu-packages-align']
  waitFor: ['yarn-common']

timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
options:
  logStreamingOption: 'STREAM_ON'
  substitution_option: 'ALLOW_LOOSE'
