#!/usr/bin/env node
// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================

const path = require('path');
const spawn = require('cross-spawn');
const shell = require('shelljs');
const argv = require('minimist')(process.argv.slice(2));

/** List of vue demos. */
const VUE_DEMOS = new Set(['vue-demo', 'latent-space-explorer']);

const demoPath = argv._[0];
const demoFolder = path.basename(demoPath);
const tsPath = path.join(demoPath, demoFolder + '.ts');
const outDir = argv._[1];

if (VUE_DEMOS.has(demoFolder)) {
  shell.cd('demos');
  const cmd = `./node_modules/.bin/poi build ${demoFolder}`;
  if (shell.exec(cmd).code !== 0) {
    shell.echo(`Failed building ${demoFolder}`);
    shell.exit(1);
  }
  return;
}

let outputPath;
if (outDir != null) {
  outputPath = path.join(outDir, demoPath, 'bundle.js');
} else {
  outputPath = path.join(demoPath, 'bundle.js')
}

const cmd = path.join('node_modules', '.bin', 'browserify');
const child = spawn(cmd,
    [tsPath, '-p', '[tsify', '-p', 'demos/tsconfig.json]', '-o' , outputPath],
    {detached: false});
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);
child.on('close', () => console.log(`Stored bundle in ${outputPath}`));
