steps:
  - name: gcr.io/learnjs-174218/release
    entrypoint: yarn
    id: yarn-common
    args:
      - install
  - name: gcr.io/learnjs-174218/release
    dir: scripts
    id: test-generate-cloudbuild
    entrypoint: yarn
    args:
      - test-generate-cloudbuild
    waitFor:
      - yarn-common
  - name: gcr.io/learnjs-174218/release
    id: test-run-flaky
    entrypoint: yarn
    args:
      - test-run-flaky
    waitFor:
      - yarn-common
  - name: gcr.io/learnjs-174218/release
    id: buildifier
    entrypoint: yarn
    args:
      - buildifier-ci
    waitFor:
      - yarn-common
  - name: gcr.io/learnjs-174218/release
    id: bazel-tests
    entrypoint: bash
    args:
      - ./scripts/run_bazel_ci_tests.sh
    env:
      - BROWSERSTACK_USERNAME=deeplearnjs1
      - NIGHTLY=$_NIGHTLY
    waitFor:
      - yarn-common
    secretEnv:
      - BROWSERSTACK_KEY
  - name: gcr.io/learnjs-174218/release
    dir: link-package-core
    entrypoint: yarn
    id: yarn-link-package-core
    args:
      - install
    waitFor:
      - bazel-tests
  - name: gcr.io/learnjs-174218/release
    dir: link-package
    entrypoint: yarn
    id: yarn-link-package
    args:
      - install
    waitFor:
      - bazel-tests
      - yarn-link-package-core
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-converter
    entrypoint: yarn
    id: yarn-tfjs-converter
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-converter
    id: lint-tfjs-converter
    entrypoint: yarn
    args:
      - lint
    waitFor:
      - yarn-tfjs-converter
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    id: create-pips-tfjs-converter
    entrypoint: bash
    args:
      - ./tfjs-converter/scripts/create_python_pips.sh
    waitFor:
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-converter/python
    entrypoint: bash
    id: test-python-pip-tfjs-converter
    args:
      - ./build-pip-package.sh
      - '--test'
      - /tmp/tfjs-pips
    waitFor:
      - create-pips-tfjs-converter
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-layers
    entrypoint: yarn
    id: yarn-tfjs-layers
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-layers
    entrypoint: yarn
    id: build-tfjs-layers
    args:
      - build-ci
    waitFor:
      - yarn-tfjs-layers
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-layers
    entrypoint: yarn
    id: lint-tfjs-layers
    args:
      - lint
    waitFor:
      - yarn-tfjs-layers
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-layers
    entrypoint: yarn
    id: test-browser-tfjs-layers
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-layers
      - lint-tfjs-layers
      - yarn-common
      - yarn-link-package
    env:
      - BROWSERSTACK_USERNAME=deeplearnjs1
      - NIGHTLY=$_NIGHTLY
    secretEnv:
      - BROWSERSTACK_KEY
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-layers
    entrypoint: yarn
    id: test-snippets-tfjs-layers
    args:
      - test-snippets-ci
    waitFor:
      - build-tfjs-layers
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-wasm
    entrypoint: yarn
    id: yarn-tfjs-backend-wasm
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-wasm
    entrypoint: bash
    id: build-tfjs-backend-wasm
    args:
      - ./scripts/build-ci.sh
    waitFor:
      - yarn-tfjs-backend-wasm
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-wasm
    entrypoint: yarn
    id: lint-tfjs-backend-wasm
    args:
      - lint
    waitFor:
      - yarn-tfjs-backend-wasm
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-wasm
    entrypoint: yarn
    id: test-wasm-tfjs-backend-wasm
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-backend-wasm
      - build-tfjs-backend-wasm
      - lint-tfjs-backend-wasm
      - yarn-common
      - yarn-link-package
    env:
      - BROWSERSTACK_USERNAME=deeplearnjs1
      - NIGHTLY=$_NIGHTLY
    secretEnv:
      - BROWSERSTACK_KEY
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-wasm
    id: test-bundle-size-tfjs-backend-wasm
    entrypoint: yarn
    args:
      - test-bundle-size
    waitFor:
      - yarn-tfjs-backend-wasm
      - build-tfjs-backend-wasm
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-webgpu
    id: yarn-tfjs-backend-webgpu
    entrypoint: yarn
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-webgpu
    id: lint-tfjs-backend-webgpu
    entrypoint: yarn
    args:
      - lint
    waitFor:
      - yarn-tfjs-backend-webgpu
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-backend-webgpu
    entrypoint: yarn
    id: test-webgpu-tfjs-backend-webgpu
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-backend-webgpu
      - lint-tfjs-backend-webgpu
      - yarn-common
      - yarn-link-package
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-data
    entrypoint: yarn
    id: yarn-tfjs-data
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-data
    entrypoint: yarn
    id: build-tfjs-data
    args:
      - build-ci
    waitFor:
      - yarn-tfjs-data
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-data
    entrypoint: yarn
    id: lint-tfjs-data
    args:
      - lint
    waitFor:
      - yarn-tfjs-data
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-data
    entrypoint: yarn
    id: test-tfjs-data
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-data
      - lint-tfjs-data
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-data
    entrypoint: yarn
    id: test-snippets-tfjs-data
    args:
      - test-snippets-ci
    waitFor:
      - build-tfjs-data
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
  - name: gcr.io/learnjs-174218/release
    dir: tfjs
    entrypoint: yarn
    id: yarn-tfjs
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
  - name: gcr.io/learnjs-174218/release
    dir: tfjs
    entrypoint: yarn
    id: build-tfjs
    args:
      - build-ci
    waitFor:
      - yarn-tfjs
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
  - name: gcr.io/learnjs-174218/release
    dir: tfjs
    entrypoint: yarn
    id: lint-tfjs
    args:
      - lint
    waitFor:
      - yarn-tfjs
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
  - name: gcr.io/learnjs-174218/release
    dir: tfjs
    entrypoint: yarn
    id: test-tfjs
    args:
      - test-ci
    waitFor:
      - yarn-tfjs
      - lint-tfjs
      - yarn-common
      - yarn-link-package
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
    env:
      - BROWSERSTACK_USERNAME=deeplearnjs1
      - NIGHTLY=$_NIGHTLY
    secretEnv:
      - BROWSERSTACK_KEY
      - FIREBASE_KEY
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: yarn-tfjs-node
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: build-addon-tfjs-node
    args:
      - build-addon-from-source
    waitFor:
      - yarn-tfjs-node
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: build-tfjs-node
    args:
      - build-ci
    waitFor:
      - yarn-tfjs-node
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: lint-tfjs-node
    args:
      - lint
    waitFor:
      - yarn-tfjs-node
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: test-tfjs-node
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-node
      - lint-tfjs-node
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node
    entrypoint: yarn
    id: ensure-cpu-gpu-packages-align-tfjs-node
    args:
      - ensure-cpu-gpu-packages-align
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    id: prep-gpu-tfjs-node-gpu
    entrypoint: yarn
    args:
      - prep-gpu
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: yarn-tfjs-node-gpu
    args:
      - install
    waitFor:
      - prep-gpu-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: build-addon-tfjs-node-gpu
    args:
      - build-addon-from-source
    waitFor:
      - yarn-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: build-tfjs-node-gpu
    args:
      - build-ci
    waitFor:
      - yarn-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: lint-tfjs-node-gpu
    args:
      - lint
    waitFor:
      - yarn-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: test-tfjs-node-gpu
    args:
      - test-ci
    waitFor:
      - yarn-tfjs-node-gpu
      - lint-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: tfjs-node-gpu
    entrypoint: yarn
    id: ensure-cpu-gpu-packages-align-tfjs-node-gpu
    args:
      - ensure-cpu-gpu-packages-align
    waitFor:
      - prep-gpu-tfjs-node-gpu
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
  - name: gcr.io/learnjs-174218/release
    dir: e2e
    entrypoint: yarn
    id: yarn-e2e
    args:
      - install
    waitFor:
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-node
      - build-addon-tfjs-node
      - build-tfjs-node
      - lint-tfjs-node
      - ensure-cpu-gpu-packages-align-tfjs-node
      - yarn-tfjs-backend-wasm
      - build-tfjs-backend-wasm
      - lint-tfjs-backend-wasm
  - name: gcr.io/learnjs-174218/release
    dir: e2e
    entrypoint: yarn
    id: test-e2e
    args:
      - test-ci
    env:
      - BROWSERSTACK_USERNAME=deeplearnjs1
      - NIGHTLY=$_NIGHTLY
    secretEnv:
      - BROWSERSTACK_KEY
    waitFor:
      - yarn-e2e
      - yarn-common
      - yarn-link-package
      - yarn-tfjs
      - build-tfjs
      - lint-tfjs
      - yarn-tfjs-converter
      - lint-tfjs-converter
      - create-pips-tfjs-converter
      - yarn-tfjs-data
      - build-tfjs-data
      - lint-tfjs-data
      - yarn-tfjs-layers
      - build-tfjs-layers
      - lint-tfjs-layers
      - yarn-tfjs-node
      - build-addon-tfjs-node
      - build-tfjs-node
      - lint-tfjs-node
      - ensure-cpu-gpu-packages-align-tfjs-node
      - yarn-tfjs-backend-wasm
      - build-tfjs-backend-wasm
      - lint-tfjs-backend-wasm
secrets:
  - kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
    secretEnv:
      BROWSERSTACK_KEY: >-
        CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
      FIREBASE_KEY: >-
        CiQAkwyoIXmET39jOD3ywloCIa6+WUpu3w49twpMmkMqy0vS+YsSUAAD8BdZQGOL8FKEBxr/1jl0G78OigwlNVHjD3usZobNtlOp8tV/9iacb8zPFqy0SwIO1gvz3HRr+VU7c7LS2qqaTCdacZF+dx3VJNewvdZu
timeout: 3600s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: STREAM_ON
  machineType: N1_HIGHCPU_32
  substitution_option: ALLOW_LOOSE
