#!/usr/bin/env node
// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================

const path = require('path');
const spawn = require('child_process').spawn;

const startTsFilePath = process.argv[2];
const startHTMLFilePath = process.argv[3];
const outDir = process.argv[4];

const cmd = path.join('scripts', 'build-demo');
const child = spawn(cmd, [startTsFilePath], {detached: false});
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);
child.on('close', () => {
  const bundlePath = path.join(outDir, path.basename(startHTMLFilePath));
  const cmd = path.join('node_modules', '.bin', 'polymer-bundler');
  const child = spawn(cmd, ['--inline-scripts', '--inline-css',
    '--out-html', bundlePath, startHTMLFilePath], {detached: false});
  child.stdout.pipe(process.stdout);
  child.stderr.pipe(process.stderr);
  child.on('close', () => console.log(`Saved bundled demo at ${bundlePath}`));
});
