steps:
# Install common dependencies.
- name: 'node:10'
  id: 'yarn-common'
  entrypoint: 'yarn'
  args: ['install']

# Install packages.
- name: 'node:10'
  dir: 'tfjs-tflite'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
  waitFor: ['yarn-common']

# Install build-deps.
- name: 'node:10'
  dir: 'tfjs-tflite'
  entrypoint: 'yarn'
  id: 'build-deps'
  args: ['build-deps-ci']
  waitFor: ['yarn-common']

# Download tfweb.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'tfjs-tflite'
  id: 'download-tfweb'
  entrypoint: 'bash'
  args: ['scripts/download-tfweb.sh']
  waitFor: ['yarn', 'build-deps']

# Build.
- name: 'node:10'
  dir: 'tfjs-tflite'
  id: 'build'
  entrypoint: 'yarn'
  args: ['build-ci']
  waitFor: ['yarn', 'build-deps', 'download-tfweb']

# Lint.
- name: 'node:10'
  dir: 'tfjs-tflite'
  entrypoint: 'yarn'
  id: 'lint'
  args: ['lint']
  waitFor: ['yarn', 'build-deps', 'download-tfweb']

# Run tests.
- name: 'node:10'
  dir: 'tfjs-tflite'
  entrypoint: 'yarn'
  id: 'test-tfjs-tflite'
  args: ['test-ci']
  waitFor: ['yarn', 'build-deps', 'lint', 'download-tfweb']
  env: ['BROWSERSTACK_USERNAME=deeplearnjs1', 'NIGHTLY=$_NIGHTLY']
  secretEnv: ['BROWSERSTACK_KEY']

# General configuration
secrets:
- kmsKeyName: projects/learnjs-174218/locations/global/keyRings/tfjs/cryptoKeys/enc
  secretEnv:
    BROWSERSTACK_KEY: CiQAkwyoIW0LcnxymzotLwaH4udVTQFBEN4AEA5CA+a3+yflL2ASPQAD8BdZnGARf78MhH5T9rQqyz9HNODwVjVIj64CTkFlUCGrP1B2HX9LXHWHLmtKutEGTeFFX9XhuBzNExA=
timeout: 3600s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
